// US Cities database for autocomplete
// Includes all major cities, towns, and populated places

export interface UsCity {
  name: string;
  state: string;
  population: number;
}

export const US_CITIES: UsCity[] = [
  // Alabama
  { name: "Birmingham", state: "AL", population: 197283 },
  { name: "Montgomery", state: "AL", population: 200603 },
  { name: "Huntsville", state: "AL", population: 215006 },
  { name: "Mobile", state: "AL", population: 184764 },
  { name: "Tuscaloosa", state: "AL", population: 101129 },
  // Alaska
  { name: "Anchorage", state: "AK", population: 291244 },
  { name: "Fairbanks", state: "AK", population: 32524 },
  { name: "Juneau", state: "AK", population: 32255 },
  // Arizona
  { name: "Phoenix", state: "AZ", population: 1608139 },
  { name: "Tucson", state: "AZ", population: 542629 },
  { name: "Mesa", state: "AZ", population: 504258 },
  { name: "Chandler", state: "AZ", population: 275987 },
  { name: "Scottsdale", state: "AZ", population: 241369 },
  { name: "Gilbert", state: "AZ", population: 267918 },
  { name: "Tempe", state: "AZ", population: 195805 },
  { name: "Peoria", state: "AZ", population: 190985 },
  { name: "Surprise", state: "AZ", population: 147961 },
  { name: "Yuma", state: "AZ", population: 93064 },
  // Arkansas
  { name: "Little Rock", state: "AR", population: 197312 },
  { name: "Fort Smith", state: "AR", population: 89602 },
  { name: "Fayetteville", state: "AR", population: 93949 },
  // California
  { name: "Los Angeles", state: "CA", population: 3979576 },
  { name: "San Diego", state: "CA", population: 1423851 },
  { name: "San Jose", state: "CA", population: 1013240 },
  { name: "San Francisco", state: "CA", population: 873965 },
  { name: "Fresno", state: "CA", population: 531219 },
  { name: "Sacramento", state: "CA", population: 524943 },
  { name: "Long Beach", state: "CA", population: 466742 },
  { name: "Oakland", state: "CA", population: 433031 },
  { name: "Bakersfield", state: "CA", population: 403455 },
  { name: "Anaheim", state: "CA", population: 350365 },
  { name: "Santa Ana", state: "CA", population: 310227 },
  { name: "Riverside", state: "CA", population: 314998 },
  { name: "Stockton", state: "CA", population: 320804 },
  { name: "Irvine", state: "CA", population: 287401 },
  { name: "Chula Vista", state: "CA", population: 275487 },
  { name: "Fremont", state: "CA", population: 230504 },
  { name: "San Bernardino", state: "CA", population: 222101 },
  { name: "Modesto", state: "CA", population: 218464 },
  { name: "Moreno Valley", state: "CA", population: 212477 },
  { name: "Fontana", state: "CA", population: 214547 },
  { name: "Santa Clarita", state: "CA", population: 228673 },
  { name: "Oxnard", state: "CA", population: 202063 },
  { name: "Glendale", state: "CA", population: 196543 },
  { name: "Huntington Beach", state: "CA", population: 198711 },
  { name: "Garden Grove", state: "CA", population: 172646 },
  { name: "Ontario", state: "CA", population: 175265 },
  { name: "Rancho Cucamonga", state: "CA", population: 177603 },
  { name: "Santa Rosa", state: "CA", population: 178127 },
  { name: "Oceanside", state: "CA", population: 176218 },
  { name: "Elk Grove", state: "CA", population: 176124 },
  { name: "Corona", state: "CA", population: 157136 },
  { name: "Lancaster", state: "CA", population: 173516 },
  { name: "Palmdale", state: "CA", population: 169450 },
  { name: "Salinas", state: "CA", population: 163542 },
  { name: "Pomona", state: "CA", population: 151713 },
  { name: "Hayward", state: "CA", population: 162954 },
  { name: "Escondido", state: "CA", population: 151038 },
  { name: "Sunnyvale", state: "CA", population: 155805 },
  { name: "Torrance", state: "CA", population: 147067 },
  { name: "Pasadena", state: "CA", population: 138699 },
  { name: "Roseville", state: "CA", population: 147773 },
  { name: "Concord", state: "CA", population: 129295 },
  { name: "Visalia", state: "CA", population: 141384 },
  { name: "Santa Clara", state: "CA", population: 127647 },
  { name: "Victorville", state: "CA", population: 134810 },
  { name: "Vallejo", state: "CA", population: 121692 },
  { name: "Berkeley", state: "CA", population: 124321 },
  { name: "El Monte", state: "CA", population: 113615 },
  { name: "Downey", state: "CA", population: 111772 },
  { name: "Costa Mesa", state: "CA", population: 112299 },
  { name: "Inglewood", state: "CA", population: 107762 },
  { name: "West Covina", state: "CA", population: 106098 },
  { name: "San Buenaventura", state: "CA", population: 109592 },
  { name: "Norwalk", state: "CA", population: 105549 },
  { name: "Carlsbad", state: "CA", population: 114746 },
  { name: "Fairfield", state: "CA", population: 119881 },
  { name: "Murrieta", state: "CA", population: 113167 },
  { name: "Temecula", state: "CA", population: 110003 },
  { name: "Richmond", state: "CA", population: 116448 },
  { name: "Burbank", state: "CA", population: 107337 },
  { name: "San Mateo", state: "CA", population: 105661 },
  { name: "Antioch", state: "CA", population: 115291 },
  { name: "Livermore", state: "CA", population: 93699 },
  { name: "Napa", state: "CA", population: 79068 },
  { name: "Redwood City", state: "CA", population: 84292 },
  // Colorado
  { name: "Denver", state: "CO", population: 715522 },
  { name: "Colorado Springs", state: "CO", population: 478961 },
  { name: "Aurora", state: "CO", population: 386261 },
  { name: "Fort Collins", state: "CO", population: 169810 },
  { name: "Lakewood", state: "CO", population: 155984 },
  { name: "Thornton", state: "CO", population: 141867 },
  { name: "Arvada", state: "CO", population: 121272 },
  { name: "Westminster", state: "CO", population: 116317 },
  { name: "Pueblo", state: "CO", population: 111876 },
  { name: "Boulder", state: "CO", population: 108250 },
  { name: "Centennial", state: "CO", population: 108418 },
  { name: "Englewood", state: "CO", population: 33659 },
  { name: "Longmont", state: "CO", population: 98885 },
  { name: "Loveland", state: "CO", population: 76378 },
  { name: "Grand Junction", state: "CO", population: 65523 },
  // Connecticut
  { name: "Bridgeport", state: "CT", population: 148654 },
  { name: "New Haven", state: "CT", population: 134023 },
  { name: "Stamford", state: "CT", population: 135470 },
  { name: "Hartford", state: "CT", population: 121054 },
  { name: "Waterbury", state: "CT", population: 114412 },
  { name: "Norwalk", state: "CT", population: 91184 },
  { name: "Danbury", state: "CT", population: 84657 },
  { name: "New Britain", state: "CT", population: 74135 },
  // Delaware
  { name: "Wilmington", state: "DE", population: 70898 },
  { name: "Dover", state: "DE", population: 39403 },
  // Florida
  { name: "Jacksonville", state: "FL", population: 949611 },
  { name: "Miami", state: "FL", population: 442241 },
  { name: "Tampa", state: "FL", population: 384959 },
  { name: "Orlando", state: "FL", population: 307573 },
  { name: "St. Petersburg", state: "FL", population: 258308 },
  { name: "Hialeah", state: "FL", population: 223166 },
  { name: "Tallahassee", state: "FL", population: 196169 },
  { name: "Fort Lauderdale", state: "FL", population: 182760 },
  { name: "Cape Coral", state: "FL", population: 194016 },
  { name: "Pembroke Pines", state: "FL", population: 171170 },
  { name: "Hollywood", state: "FL", population: 153259 },
  { name: "Gainesville", state: "FL", population: 141347 },
  { name: "Miramar", state: "FL", population: 134712 },
  { name: "Coral Springs", state: "FL", population: 134046 },
  { name: "Clearwater", state: "FL", population: 117292 },
  { name: "Miami Gardens", state: "FL", population: 113058 },
  { name: "Palm Bay", state: "FL", population: 114021 },
  { name: "West Palm Beach", state: "FL", population: 117415 },
  { name: "Pompano Beach", state: "FL", population: 112118 },
  { name: "Lakewood Ranch", state: "FL", population: 41023 },
  { name: "Naples", state: "FL", population: 21889 },
  { name: "Sarasota", state: "FL", population: 59521 },
  { name: "Fort Myers", state: "FL", population: 86395 },
  // Georgia
  { name: "Atlanta", state: "GA", population: 498715 },
  { name: "Augusta", state: "GA", population: 197166 },
  { name: "Columbus", state: "GA", population: 206922 },
  { name: "Savannah", state: "GA", population: 147780 },
  { name: "Athens", state: "GA", population: 127315 },
  { name: "Macon", state: "GA", population: 157422 },
  { name: "Roswell", state: "GA", population: 92833 },
  { name: "Alpharetta", state: "GA", population: 65818 },
  { name: "Marietta", state: "GA", population: 60981 },
  // Hawaii
  { name: "Honolulu", state: "HI", population: 350964 },
  { name: "Pearl City", state: "HI", population: 47698 },
  { name: "Hilo", state: "HI", population: 45235 },
  // Idaho
  { name: "Boise", state: "ID", population: 235684 },
  { name: "Meridian", state: "ID", population: 125963 },
  { name: "Nampa", state: "ID", population: 100200 },
  { name: "Idaho Falls", state: "ID", population: 64818 },
  // Illinois
  { name: "Chicago", state: "IL", population: 2693976 },
  { name: "Aurora", state: "IL", population: 197899 },
  { name: "Naperville", state: "IL", population: 149540 },
  { name: "Joliet", state: "IL", population: 150372 },
  { name: "Rockford", state: "IL", population: 148655 },
  { name: "Springfield", state: "IL", population: 114394 },
  { name: "Peoria", state: "IL", population: 113150 },
  { name: "Elgin", state: "IL", population: 114797 },
  { name: "Champaign", state: "IL", population: 88302 },
  // Indiana
  { name: "Indianapolis", state: "IN", population: 887642 },
  { name: "Fort Wayne", state: "IN", population: 270402 },
  { name: "Evansville", state: "IN", population: 117256 },
  { name: "South Bend", state: "IN", population: 103453 },
  { name: "Carmel", state: "IN", population: 99711 },
  // Iowa
  { name: "Des Moines", state: "IA", population: 215559 },
  { name: "Cedar Rapids", state: "IA", population: 137710 },
  { name: "Davenport", state: "IA", population: 101724 },
  // Kansas
  { name: "Wichita", state: "KS", population: 397532 },
  { name: "Overland Park", state: "KS", population: 197238 },
  { name: "Kansas City", state: "KS", population: 156607 },
  { name: "Olathe", state: "KS", population: 140526 },
  // Kentucky
  { name: "Louisville", state: "KY", population: 633045 },
  { name: "Lexington", state: "KY", population: 322570 },
  { name: "Bowling Green", state: "KY", population: 72294 },
  // Louisiana
  { name: "New Orleans", state: "LA", population: 391495 },
  { name: "Baton Rouge", state: "LA", population: 227470 },
  { name: "Shreveport", state: "LA", population: 187593 },
  { name: "Lafayette", state: "LA", population: 126805 },
  // Maine
  { name: "Portland", state: "ME", population: 68408 },
  { name: "Lewiston", state: "ME", population: 36221 },
  // Maryland
  { name: "Baltimore", state: "MD", population: 585708 },
  { name: "Frederick", state: "MD", population: 78385 },
  { name: "Rockville", state: "MD", population: 67178 },
  { name: "Gaithersburg", state: "MD", population: 69674 },
  { name: "Bowie", state: "MD", population: 58318 },
  { name: "Hagerstown", state: "MD", population: 43510 },
  // Massachusetts
  { name: "Boston", state: "MA", population: 692600 },
  { name: "Worcester", state: "MA", population: 206518 },
  { name: "Springfield", state: "MA", population: 155032 },
  { name: "Cambridge", state: "MA", population: 118977 },
  { name: "Lowell", state: "MA", population: 115554 },
  { name: "Somerville", state: "MA", population: 81360 },
  // Michigan
  { name: "Detroit", state: "MI", population: 639111 },
  { name: "Grand Rapids", state: "MI", population: 198917 },
  { name: "Warren", state: "MI", population: 139387 },
  { name: "Sterling Heights", state: "MI", population: 134346 },
  { name: "Ann Arbor", state: "MI", population: 123851 },
  { name: "Lansing", state: "MI", population: 112644 },
  // Minnesota
  { name: "Minneapolis", state: "MN", population: 429954 },
  { name: "Saint Paul", state: "MN", population: 311527 },
  { name: "Rochester", state: "MN", population: 121395 },
  { name: "Bloomington", state: "MN", population: 89987 },
  { name: "Plymouth", state: "MN", population: 81223 },
  // Mississippi
  { name: "Jackson", state: "MS", population: 149768 },
  { name: "Gulfport", state: "MS", population: 72926 },
  { name: "Southaven", state: "MS", population: 59334 },
  // Missouri
  { name: "Kansas City", state: "MO", population: 508090 },
  { name: "Saint Louis", state: "MO", population: 301578 },
  { name: "Springfield", state: "MO", population: 169176 },
  { name: "Columbia", state: "MO", population: 126254 },
  { name: "Independence", state: "MO", population: 123011 },
  // Montana
  { name: "Billings", state: "MT", population: 119719 },
  { name: "Missoula", state: "MT", population: 75510 },
  // Nebraska
  { name: "Omaha", state: "NE", population: 487300 },
  { name: "Lincoln", state: "NE", population: 295178 },
  // Nevada
  { name: "Las Vegas", state: "NV", population: 641903 },
  { name: "Henderson", state: "NV", population: 320189 },
  { name: "Reno", state: "NV", population: 264491 },
  { name: "North Las Vegas", state: "NV", population: 262561 },
  { name: "Sparks", state: "NV", population: 108445 },
  // New Hampshire
  { name: "Manchester", state: "NH", population: 115644 },
  { name: "Nashua", state: "NH", population: 91322 },
  // New Jersey
  { name: "Newark", state: "NJ", population: 311549 },
  { name: "Jersey City", state: "NJ", population: 292446 },
  { name: "Paterson", state: "NJ", population: 159732 },
  { name: "Elizabeth", state: "NJ", population: 137191 },
  { name: "Edison", state: "NJ", population: 107529 },
  { name: "Woodbridge", state: "NJ", population: 103639 },
  { name: "Lakewood", state: "NJ", population: 102682 },
  { name: "Hamilton", state: "NJ", population: 92297 },
  { name: "Trenton", state: "NJ", population: 84964 },
  { name: "Camden", state: "NJ", population: 71791 },
  { name: "Cherry Hill", state: "NJ", population: 71045 },
  // New Mexico
  { name: "Albuquerque", state: "NM", population: 564559 },
  { name: "Las Cruces", state: "NM", population: 111385 },
  { name: "Santa Fe", state: "NM", population: 87600 },
  // New York
  { name: "New York City", state: "NY", population: 8336817 },
  { name: "Buffalo", state: "NY", population: 278349 },
  { name: "Rochester", state: "NY", population: 211328 },
  { name: "Yonkers", state: "NY", population: 211577 },
  { name: "Syracuse", state: "NY", population: 148620 },
  { name: "Albany", state: "NY", population: 99224 },
  { name: "New Rochelle", state: "NY", population: 80558 },
  { name: "Mount Vernon", state: "NY", population: 73810 },
  { name: "Schenectady", state: "NY", population: 68489 },
  // North Carolina
  { name: "Charlotte", state: "NC", population: 874579 },
  { name: "Raleigh", state: "NC", population: 474069 },
  { name: "Durham", state: "NC", population: 283506 },
  { name: "Greensboro", state: "NC", population: 296710 },
  { name: "Winston-Salem", state: "NC", population: 249545 },
  { name: "Fayetteville", state: "NC", population: 211657 },
  { name: "Cary", state: "NC", population: 174721 },
  { name: "Wilmington", state: "NC", population: 123744 },
  { name: "High Point", state: "NC", population: 114059 },
  // North Dakota
  { name: "Fargo", state: "ND", population: 125990 },
  { name: "Bismarck", state: "ND", population: 73622 },
  // Ohio
  { name: "Columbus", state: "OH", population: 905748 },
  { name: "Cleveland", state: "OH", population: 372624 },
  { name: "Cincinnati", state: "OH", population: 309317 },
  { name: "Toledo", state: "OH", population: 270871 },
  { name: "Akron", state: "OH", population: 190469 },
  { name: "Dayton", state: "OH", population: 137644 },
  { name: "Parma", state: "OH", population: 81075 },
  // Oklahoma
  { name: "Oklahoma City", state: "OK", population: 681054 },
  { name: "Tulsa", state: "OK", population: 413066 },
  { name: "Norman", state: "OK", population: 128026 },
  { name: "Broken Arrow", state: "OK", population: 113540 },
  // Oregon
  { name: "Portland", state: "OR", population: 652503 },
  { name: "Eugene", state: "OR", population: 176654 },
  { name: "Salem", state: "OR", population: 175535 },
  { name: "Gresham", state: "OR", population: 111520 },
  { name: "Hillsboro", state: "OR", population: 106674 },
  // Pennsylvania
  { name: "Philadelphia", state: "PA", population: 1603797 },
  { name: "Pittsburgh", state: "PA", population: 302971 },
  { name: "Allentown", state: "PA", population: 125845 },
  { name: "Erie", state: "PA", population: 94831 },
  { name: "Reading", state: "PA", population: 95112 },
  { name: "Scranton", state: "PA", population: 76653 },
  // Rhode Island
  { name: "Providence", state: "RI", population: 190934 },
  { name: "Warwick", state: "RI", population: 82823 },
  // South Carolina
  { name: "Charleston", state: "SC", population: 150227 },
  { name: "Columbia", state: "SC", population: 136632 },
  { name: "North Charleston", state: "SC", population: 113237 },
  { name: "Mount Pleasant", state: "SC", population: 93107 },
  { name: "Rock Hill", state: "SC", population: 74372 },
  // South Dakota
  { name: "Sioux Falls", state: "SD", population: 192517 },
  { name: "Rapid City", state: "SD", population: 78435 },
  // Tennessee
  { name: "Nashville", state: "TN", population: 689447 },
  { name: "Memphis", state: "TN", population: 633104 },
  { name: "Knoxville", state: "TN", population: 192648 },
  { name: "Murfreesboro", state: "TN", population: 152722 },
  { name: "Chattanooga", state: "TN", population: 184440 },
  { name: "Clarksville", state: "TN", population: 160647 },
  // Texas
  { name: "Houston", state: "TX", population: 2304580 },
  { name: "San Antonio", state: "TX", population: 1434625 },
  { name: "Dallas", state: "TX", population: 1343573 },
  { name: "Austin", state: "TX", population: 979882 },
  { name: "Fort Worth", state: "TX", population: 918915 },
  { name: "El Paso", state: "TX", population: 678815 },
  { name: "Arlington", state: "TX", population: 394266 },
  { name: "Corpus Christi", state: "TX", population: 317863 },
  { name: "Plano", state: "TX", population: 285494 },
  { name: "Laredo", state: "TX", population: 255473 },
  { name: "Lubbock", state: "TX", population: 264362 },
  { name: "Garland", state: "TX", population: 246018 },
  { name: "Irving", state: "TX", population: 256684 },
  { name: "Frisco", state: "TX", population: 200509 },
  { name: "Amarillo", state: "TX", population: 200682 },
  { name: "Grand Prairie", state: "TX", population: 196100 },
  { name: "McKinney", state: "TX", population: 199177 },
  { name: "Brownsville", state: "TX", population: 186738 },
  { name: "Killeen", state: "TX", population: 156334 },
  { name: "Pasadena", state: "TX", population: 151950 },
  { name: "Mesquite", state: "TX", population: 150108 },
  { name: "McAllen", state: "TX", population: 142210 },
  { name: "Midland", state: "TX", population: 132950 },
  { name: "Denton", state: "TX", population: 148146 },
  { name: "Waco", state: "TX", population: 139236 },
  { name: "Carrollton", state: "TX", population: 137834 },
  { name: "Round Rock", state: "TX", population: 133372 },
  { name: "Abilene", state: "TX", population: 125182 },
  { name: "Pearland", state: "TX", population: 125828 },
  { name: "Richardson", state: "TX", population: 121323 },
  { name: "Odessa", state: "TX", population: 127160 },
  { name: "Sugar Land", state: "TX", population: 111026 },
  { name: "Beaumont", state: "TX", population: 115282 },
  { name: "Lewisville", state: "TX", population: 111822 },
  // Utah
  { name: "Salt Lake City", state: "UT", population: 200133 },
  { name: "West Valley City", state: "UT", population: 140236 },
  { name: "Provo", state: "UT", population: 117335 },
  { name: "West Jordan", state: "UT", population: 116101 },
  { name: "Orem", state: "UT", population: 98129 },
  { name: "Sandy", state: "UT", population: 96901 },
  { name: "St. George", state: "UT", population: 95331 },
  // Vermont
  { name: "Burlington", state: "VT", population: 44743 },
  // Virginia
  { name: "Virginia Beach", state: "VA", population: 459470 },
  { name: "Norfolk", state: "VA", population: 238005 },
  { name: "Chesapeake", state: "VA", population: 249422 },
  { name: "Richmond", state: "VA", population: 230436 },
  { name: "Arlington", state: "VA", population: 234965 },
  { name: "Alexandria", state: "VA", population: 159428 },
  { name: "Roanoke", state: "VA", population: 100011 },
  // Washington
  { name: "Seattle", state: "WA", population: 737015 },
  { name: "Spokane", state: "WA", population: 228989 },
  { name: "Tacoma", state: "WA", population: 219346 },
  { name: "Vancouver", state: "WA", population: 190915 },
  { name: "Bellevue", state: "WA", population: 151580 },
  { name: "Kent", state: "WA", population: 136588 },
  { name: "Everett", state: "WA", population: 113444 },
  { name: "Renton", state: "WA", population: 106601 },
  // West Virginia
  { name: "Charleston", state: "WV", population: 46536 },
  { name: "Huntington", state: "WV", population: 46048 },
  // Wisconsin
  { name: "Milwaukee", state: "WI", population: 577222 },
  { name: "Madison", state: "WI", population: 259680 },
  { name: "Green Bay", state: "WI", population: 107015 },
  { name: "Kenosha", state: "WI", population: 100433 },
  // Wyoming
  { name: "Cheyenne", state: "WY", population: 65132 },
  { name: "Casper", state: "WY", population: 59781 },
];

// Niche categories for search
export const NICHE_CATEGORIES = [
  "Auto Repair",
  "Coach",
  "Dental",
  "Gym",
  "Hair Salon",
  "Home Services",
  "Massage",
  "Nail Salon",
  "Pet Services",
  "Cleaning",
  "Plumbing",
  "Electrician",
  "HVAC",
  "Roofing",
  "Landscaping",
  "Painting",
  "Real Estate",
  "Insurance",
  "Accounting",
  "Legal",
  "Marketing",
  "IT Services",
  "Restaurant",
  "Cafe",
  "Bar",
  "Hotel",
  "Spa",
  "Yoga Studio",
  "CrossFit",
  "Personal Training",
  "Photography",
  "Event Planning",
  "Wedding Planning",
  "Florist",
  "Bakery",
  "Car Wash",
  "Towing",
  "Moving Services",
  "Storage",
  "Printing",
  "Signage",
  "Custom",
] as const;

export type NicheCategory = (typeof NICHE_CATEGORIES)[number];
