"""Liam Orchestrator — AI-powered lead search orchestrator.

Responsibilities:
  1. Generate search queries (dorks) from user input
  2. Validate and deduplicate found contacts
  3. Score and rank leads
  4. Write structured leads to Supabase
"""

import json
import logging
import os
import re
from dataclasses import dataclass, field
from typing import Any

import httpx

logger = logging.getLogger(__name__)


@dataclass
class GeneratedQuery:
    """A single search query generated by Liam."""
    query: str
    platform: str = "google"  # google, linkedin, yelp, etc.
    priority: int = 1


@dataclass
class ValidatedContact:
    """A validated contact extracted from web scraping."""
    email: str | None = None
    phone: str | None = None
    website: str | None = None
    social_links: dict[str, str] = field(default_factory=dict)
    company_name: str = ""
    source_url: str = ""


class LiamOrchestrator:
    """Orchestrates lead search: query generation, validation, scoring, storage.

    Supports two LLM backends:
      - Ollama (local, default): http://localhost:11434/v1
      - OpenAI (cloud, fallback): api.openai.com
    """

    def __init__(
        self,
        ollama_url: str | None = None,
        ollama_model: str = "llama3.2",
        provider: str | None = None,
    ):
        self.provider = provider or os.getenv("LLM_PROVIDER", "ollama")
        self.ollama_url = ollama_url or os.getenv("OLLAMA_URL", "http://localhost:11434/v1")
        self.model = ollama_model
        self.openai_api_key = os.getenv("OPENAI_API_KEY")
        self.openai_model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
        self._client: httpx.AsyncClient | None = None

    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None:
            self._client = httpx.AsyncClient(timeout=60.0)
        return self._client

    async def close(self):
        if self._client:
            await self._client.aclose()
            self._client = None

    async def _call_llm(self, prompt: str, system_prompt: str = "") -> str:
        client = await self._get_client()
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        # Try Ollama first, fallback to OpenAI
        providers = ["ollama"] if self.provider == "ollama" else ["ollama", "openai"]

        for provider in providers:
            try:
                if provider == "ollama":
                    response = await client.post(
                        f"{self.ollama_url}/chat/completions",
                        json={
                            "model": self.model,
                            "messages": messages,
                            "max_tokens": 2048,
                            "temperature": 0.2,
                        },
                    )
                    response.raise_for_status()
                    return response.json()["choices"][0]["message"]["content"]
                elif provider == "openai" and self.openai_api_key:
                    response = await client.post(
                        "https://api.openai.com/v1/chat/completions",
                        headers={"Authorization": f"Bearer {self.openai_api_key}"},
                        json={
                            "model": self.openai_model,
                            "messages": messages,
                            "max_tokens": 2048,
                            "temperature": 0.2,
                        },
                    )
                    response.raise_for_status()
                    return response.json()["choices"][0]["message"]["content"]
            except Exception as e:
                logger.warning(f"LLM call failed ({provider}): {e}")
                if provider == providers[-1]:
                    raise

        raise RuntimeError("No LLM provider available")

    # ========================================
    # Query Generation
    # ========================================

    async def generate_search_queries(
        self, city: str, niche: str, max_queries: int = 5
    ) -> list[GeneratedQuery]:
        """Generate Google dorks and search queries from city + niche."""

        system_prompt = """You are an expert B2B lead generation researcher.
Given a city and industry niche, generate effective Google search queries (dorks)
to find potential business contacts.

Return a JSON array of objects with:
- query: the search query string
- platform: "google", "linkedin", "yelp", "google_maps"
- priority: 1 (highest) to 5 (lowest)

Focus on:
- Finding official websites with contact pages
- LinkedIn company profiles
- Google Maps listings
- Yelp or industry-specific directories
- Avoid irrelevant results"""

        user_prompt = f"""Generate {max_queries} search queries for:
City: {city}
Niche: {niche}

Example format:
[
  {{"query": "real estate agency Dubai contact email phone", "platform": "google", "priority": 1}},
  {{"query": "site:linkedin.com company \"real estate\" Dubai", "platform": "linkedin", "priority": 2}},
  {{"query": "real estate agency Dubai site:yelp.com", "platform": "yelp", "priority": 3}}
]"""

        try:
            response = await self._call_llm(user_prompt, system_prompt)
            data = json.loads(response)
            queries = []
            for item in data[:max_queries]:
                queries.append(GeneratedQuery(
                    query=item.get("query", ""),
                    platform=item.get("platform", "google"),
                    priority=item.get("priority", 3),
                ))
            return sorted(queries, key=lambda q: q.priority)
        except Exception as e:
            logger.warning(f"Query generation failed, using fallback: {e}")
            return [
                GeneratedQuery(query=f"{niche} {city} contact email phone", platform="google", priority=1),
                GeneratedQuery(query=f"site:linkedin.com {niche} {city}", platform="linkedin", priority=2),
                GeneratedQuery(query=f"{niche} {city} site:yelp.com", platform="yelp", priority=3),
            ]

    # ========================================
    # Contact Validation
    # ========================================

    def validate_email(self, email: str) -> bool:
        """Validate email format."""
        if not email:
            return False
        pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        return bool(re.match(pattern, email.strip()))

    def validate_phone(self, phone: str) -> bool:
        """Validate phone number format."""
        if not phone:
            return False
        cleaned = re.sub(r'[\s\-\(\)\+]', '', phone)
        return len(cleaned) >= 7 and cleaned.isdigit()

    def extract_contacts_from_html(self, html: str, url: str) -> ValidatedContact:
        """Extract and validate contacts from raw HTML/text content."""
        contact = ValidatedContact(source_url=url)

        # Extract emails
        emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', html)
        valid_emails = [e for e in emails if self.validate_email(e)]
        # Filter out common non-business emails
        filtered_emails = [
            e for e in valid_emails
            if not any(x in e.lower() for x in ['@sentry', '@example', 'noreply', 'no-reply'])
        ]
        if filtered_emails:
            contact.email = filtered_emails[0]

        # Extract phones (international format)
        phones = re.findall(r'(?:\+?\d{1,3}[\s\-]?)?\(?\d{2,4}\)?[\s\-]?\d{3,4}[\s\-]?\d{3,4}', html)
        valid_phones = [p.strip() for p in phones if self.validate_phone(p)]
        if valid_phones:
            contact.phone = valid_phones[0]

        # Extract website
        website_match = re.search(r'href="(https?://[^"]*)"', html)
        if website_match:
            contact.website = website_match.group(1)

        # Extract social links
        social_patterns = {
            'linkedin': r'(https?://(?:www\.)?linkedin\.com/(?:company|in)/[^\s"\'<>]+)',
            'telegram': r'(https?://(?:t\.me|telegram\.me)/[^\s"\'<>]+)',
            'whatsapp': r'(https?://(?:wa\.me|api\.whatsapp\.com/send)[^\s"\'<>]+)',
            'instagram': r'(https?://(?:www\.)?instagram\.com/[^\s"\'<>]+)',
            'facebook': r'(https?://(?:www\.)?facebook\.com/[^\s"\'<>]+)',
        }
        for platform, pattern in social_patterns.items():
            match = re.search(pattern, html)
            if match:
                contact.social_links[platform] = match.group(1)

        return contact

    # ========================================
    # Lead Scoring
    # ========================================

    async def score_lead(
        self, contact: ValidatedContact, niche: str, city: str
    ) -> int:
        """Score a lead 1-10 based on data completeness and relevance."""

        score = 0

        # Contact completeness (max 6 points)
        if contact.email:
            score += 2
        if contact.phone:
            score += 2
        if contact.website:
            score += 1
        if contact.social_links:
            score += min(len(contact.social_links), 1)

        # Company name present (+1)
        if contact.company_name:
            score += 1

        # Source URL present (+1)
        if contact.source_url:
            score += 1

        # Social presence bonus (+1 for 2+ social links)
        if len(contact.social_links) >= 2:
            score += 1

        return min(score, 10)

    # ========================================
    # Deduplication
    # ========================================

    def deduplicate_contacts(
        self, contacts: list[ValidatedContact]
    ) -> list[ValidatedContact]:
        """Remove duplicate contacts based on email and phone."""
        seen_emails: set[str] = set()
        seen_phones: set[str] = set()
        unique: list[ValidatedContact] = []

        for contact in contacts:
            email_key = contact.email.lower().strip() if contact.email else ""
            phone_key = re.sub(r'\D', '', contact.phone) if contact.phone else ""

            if email_key and email_key in seen_emails:
                continue
            if phone_key and phone_key in seen_phones:
                continue

            if email_key:
                seen_emails.add(email_key)
            if phone_key:
                seen_phones.add(phone_key)
            unique.append(contact)

        return unique

    # ========================================
    # Database Storage
    # ========================================

    async def save_leads_to_db(
        self,
        contacts: list[ValidatedContact],
        user_id: str,
        source_query: str = "",
        niche: str = "",
        city: str = "",
        country: str = "United States",
    ) -> list[dict]:
        """Save validated contacts to the lead_clients table in Supabase."""
        try:
            from backend.services.supabase_client import supabase_service
        except ImportError:
            logger.error("Cannot import supabase_service")
            return []

        saved_leads = []

        for contact in contacts:
            score = await self.score_lead(contact, niche, city)

            # Determine website status
            website_status = "no_website"
            if contact.website:
                website_status = "good"  # Could be enhanced with AI analysis

            lead_data = {
                "user_id": user_id,
                "business_name": contact.company_name or "Unknown",
                "category": niche,
                "city_location": city,
                "country": country,
                "country_flag": "🇺🇸",
                "contact_phone": contact.phone,
                "email": contact.email or "-",
                "website_url": contact.website or "-",
                "whatsapp_status": "Unverified",
                "google_maps_url": None,
                "priority": "High" if score >= 7 else "Middle" if score >= 4 else "Low",
                "status": "Lead",
                "website_status_type": website_status,
                "ai_offer_script": None,  # Will be generated by Liam
                "source_query": source_query,
            }

            try:
                result = supabase_service.client.table("lead_clients").insert(lead_data).execute()
                if result.data:
                    saved_leads.append(result.data[0])
                    logger.info(f"Saved lead: {contact.company_name} ({city})")
            except Exception as e:
                logger.error(f"Failed to save lead '{contact.company_name}': {e}")

        return saved_leads
