/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LeadSearchRouteImport } from './routes/lead-search'
import { Route as MailRouteImport } from './routes/mail'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadSearchRoute = LeadSearchRouteImport.update({
  id: '/lead-search',
  path: '/lead-search',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/finance': typeof FinanceRoute
  '/lead-search': typeof LeadSearchRoute
  '/mail': typeof MailRoute
  '/projects': typeof ProjectsRoute
  '/requests': typeof RequestsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/finance': typeof FinanceRoute
  '/lead-search': typeof LeadSearchRoute
  '/mail': typeof MailRoute
  '/projects': typeof ProjectsRoute
  '/requests': typeof RequestsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/finance': typeof FinanceRoute
  '/lead-search': typeof LeadSearchRoute
  '/mail': typeof MailRoute
  '/projects': typeof ProjectsRoute
  '/requests': typeof RequestsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/calendar'
    | '/clients'
    | '/finance'
    | '/lead-search'
    | '/mail'
    | '/projects'
    | '/requests'
    | '/tasks'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/calendar'
    | '/clients'
    | '/finance'
    | '/lead-search'
    | '/mail'
    | '/projects'
    | '/requests'
    | '/tasks'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/calendar'
    | '/clients'
    | '/finance'
    | '/lead-search'
    | '/mail'
    | '/projects'
    | '/requests'
    | '/tasks'
    | '/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRoute
  FinanceRoute: typeof FinanceRoute
  LeadSearchRoute: typeof LeadSearchRoute
  MailRoute: typeof MailRoute
  ProjectsRoute: typeof ProjectsRoute
  RequestsRoute: typeof RequestsRoute
  TasksRoute: typeof TasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-search': {
      id: '/lead-search'
      path: '/lead-search'
      fullPath: '/lead-search'
      preLoaderRoute: typeof LeadSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
  }
}

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRoute,
  FinanceRoute: FinanceRoute,
  LeadSearchRoute: LeadSearchRoute,
  MailRoute: MailRoute,
  ProjectsRoute: ProjectsRoute,
  RequestsRoute: RequestsRoute,
  TasksRoute: TasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
