/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiWorkflowRouteImport } from './routes/ai-workflow'
import { Route as BookRouteImport } from './routes/book'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LeadSearchRouteImport } from './routes/lead-search'
import { Route as MailRouteImport } from './routes/mail'
import { Route as OpenclawTasksRouteImport } from './routes/openclaw-tasks'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PromptGeneratorRouteImport } from './routes/prompt-generator'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SelfDevelopmentRouteImport } from './routes/self-development'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ApiLeadSearchRouteImport } from './routes/api/lead-search'
import { Route as ApiNvidiaChatRouteImport } from './routes/api/nvidia-chat'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as ApiAiWorkflowSplatRouteImport } from './routes/api/ai-workflow/$'
import { Route as ApiAiAnalyzeTasksRouteImport } from './routes/api/ai/analyze-tasks'
import { Route as ApiBackendSplatRouteImport } from './routes/api/backend/$'
import { Route as ApiLearningSplatRouteImport } from './routes/api/learning/$'
import { Route as ApiMailSplatRouteImport } from './routes/api/mail/$'
import { Route as ApiOpenclawSplatRouteImport } from './routes/api/openclaw/$'
import { Route as ApiSpeechTranscribeRouteImport } from './routes/api/speech/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkflowRoute = AiWorkflowRouteImport.update({
  id: '/ai-workflow',
  path: '/ai-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadSearchRoute = LeadSearchRouteImport.update({
  id: '/lead-search',
  path: '/lead-search',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenclawTasksRoute = OpenclawTasksRouteImport.update({
  id: '/openclaw-tasks',
  path: '/openclaw-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptGeneratorRoute = PromptGeneratorRouteImport.update({
  id: '/prompt-generator',
  path: '/prompt-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfDevelopmentRoute = SelfDevelopmentRouteImport.update({
  id: '/self-development',
  path: '/self-development',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadSearchRoute = ApiLeadSearchRouteImport.update({
  id: '/api/lead-search',
  path: '/api/lead-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNvidiaChatRoute = ApiNvidiaChatRouteImport.update({
  id: '/api/nvidia-chat',
  path: '/api/nvidia-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const ApiAiWorkflowSplatRoute = ApiAiWorkflowSplatRouteImport.update({
  id: '/api/ai-workflow/$',
  path: '/api/ai-workflow/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAnalyzeTasksRoute = ApiAiAnalyzeTasksRouteImport.update({
  id: '/api/ai/analyze-tasks',
  path: '/api/ai/analyze-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackendSplatRoute = ApiBackendSplatRouteImport.update({
  id: '/api/backend/$',
  path: '/api/backend/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningSplatRoute = ApiLearningSplatRouteImport.update({
  id: '/api/learning/$',
  path: '/api/learning/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailSplatRoute = ApiMailSplatRouteImport.update({
  id: '/api/mail/$',
  path: '/api/mail/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenclawSplatRoute = ApiOpenclawSplatRouteImport.update({
  id: '/api/openclaw/$',
  path: '/api/openclaw/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechTranscribeRoute = ApiSpeechTranscribeRouteImport.update({
  id: '/api/speech/transcribe',
  path: '/api/speech/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-workflow': typeof AiWorkflowRoute
  '/book': typeof BookRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/finance': typeof FinanceRoute
  '/prompt-generator': typeof PromptGeneratorRoute
  '/lead-search': typeof LeadSearchRoute
  '/mail': typeof MailRoute
  '/openclaw-tasks': typeof OpenclawTasksRoute
  '/projects': typeof ProjectsRoute
  '/prompt-generator': typeof PromptGeneratorRoute
  '/requests': typeof RequestsRoute
  '/self-development': typeof SelfDevelopmentRoute
  '/tasks': typeof TasksRouteWithChildren
  '/api/lead-search': typeof ApiLeadSearchRoute
  '/api/nvidia-chat': typeof ApiNvidiaChatRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/ai-workflow/$': typeof ApiAiWorkflowSplatRoute
  '/api/ai/analyze-tasks': typeof ApiAiAnalyzeTasksRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
  '/api/learning/$': typeof ApiLearningSplatRoute
  '/api/mail/$': typeof ApiMailSplatRoute
  '/api/openclaw/$': typeof ApiOpenclawSplatRoute
  '/api/speech/transcribe': typeof ApiSpeechTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-workflow': typeof AiWorkflowRoute
  '/book': typeof BookRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/finance': typeof FinanceRoute
  '/prompt-generator': typeof PromptGeneratorRoute
  '/lead-search': typeof LeadSearchRoute
  '/mail': typeof MailRoute
  '/openclaw-tasks': typeof OpenclawTasksRoute
  '/projects': typeof ProjectsRoute
  '/prompt-generator': typeof PromptGeneratorRoute
  '/requests': typeof RequestsRoute
  '/self-development': typeof SelfDevelopmentRoute
  '/tasks': typeof TasksRouteWithChildren
  '/api/lead-search': typeof ApiLeadSearchRoute
  '/api/nvidia-chat': typeof ApiNvidiaChatRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/ai-workflow/$': typeof ApiAiWorkflowSplatRoute
  '/api/ai/analyze-tasks': typeof ApiAiAnalyzeTasksRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
  '/api/learning/$': typeof ApiLearningSplatRoute
  '/api/mail/$': typeof ApiMailSplatRoute
  '/api/openclaw/$': typeof ApiOpenclawSplatRoute
  '/api/speech/transcribe': typeof ApiSpeechTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-workflow': typeof AiWorkflowRoute
  '/book': typeof BookRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/finance': typeof FinanceRoute
  '/prompt-generator': typeof PromptGeneratorRoute
  '/lead-search': typeof LeadSearchRoute
  '/mail': typeof MailRoute
  '/openclaw-tasks': typeof OpenclawTasksRoute
  '/projects': typeof ProjectsRoute
  '/prompt-generator': typeof PromptGeneratorRoute
  '/requests': typeof RequestsRoute
  '/self-development': typeof SelfDevelopmentRoute
  '/tasks': typeof TasksRouteWithChildren
  '/api/lead-search': typeof ApiLeadSearchRoute
  '/api/nvidia-chat': typeof ApiNvidiaChatRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/ai-workflow/$': typeof ApiAiWorkflowSplatRoute
  '/api/ai/analyze-tasks': typeof ApiAiAnalyzeTasksRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
  '/api/learning/$': typeof ApiLearningSplatRoute
  '/api/mail/$': typeof ApiMailSplatRoute
  '/api/openclaw/$': typeof ApiOpenclawSplatRoute
  '/api/speech/transcribe': typeof ApiSpeechTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-workflow'
    | '/book'
    | '/calendar'
    | '/clients'
    | '/finance'
    | '/lead-search'
    | '/mail'
    | '/openclaw-tasks'
    | '/projects'
    | '/prompt-generator'
    | '/requests'
    | '/self-development'
    | '/tasks'
    | '/api/lead-search'
    | '/api/nvidia-chat'
    | '/tasks/$taskId'
    | '/api/ai-workflow/$'
    | '/api/ai/analyze-tasks'
    | '/api/backend/$'
    | '/api/learning/$'
    | '/api/mail/$'
    | '/api/openclaw/$'
    | '/api/speech/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-workflow'
    | '/book'
    | '/calendar'
    | '/clients'
    | '/finance'
    | '/lead-search'
    | '/mail'
    | '/openclaw-tasks'
    | '/projects'
    | '/prompt-generator'
    | '/requests'
    | '/self-development'
    | '/tasks'
    | '/api/lead-search'
    | '/api/nvidia-chat'
    | '/tasks/$taskId'
    | '/api/ai-workflow/$'
    | '/api/ai/analyze-tasks'
    | '/api/backend/$'
    | '/api/learning/$'
    | '/api/mail/$'
    | '/api/openclaw/$'
    | '/api/speech/transcribe'
  id:
    | '__root__'
    | '/'
    | '/ai-workflow'
    | '/book'
    | '/calendar'
    | '/clients'
    | '/finance'
    | '/lead-search'
    | '/mail'
    | '/openclaw-tasks'
    | '/projects'
    | '/prompt-generator'
    | '/requests'
    | '/self-development'
    | '/tasks'
    | '/api/lead-search'
    | '/api/nvidia-chat'
    | '/tasks/$taskId'
    | '/api/ai-workflow/$'
    | '/api/ai/analyze-tasks'
    | '/api/backend/$'
    | '/api/learning/$'
    | '/api/mail/$'
    | '/api/openclaw/$'
    | '/api/speech/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiWorkflowRoute: typeof AiWorkflowRoute
  BookRoute: typeof BookRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRoute
  FinanceRoute: typeof FinanceRoute
  LeadSearchRoute: typeof LeadSearchRoute
  MailRoute: typeof MailRoute
  OpenclawTasksRoute: typeof OpenclawTasksRoute
  ProjectsRoute: typeof ProjectsRoute
  PromptGeneratorRoute: typeof PromptGeneratorRoute
  RequestsRoute: typeof RequestsRoute
  SelfDevelopmentRoute: typeof SelfDevelopmentRoute
  TasksRoute: typeof TasksRouteWithChildren
  ApiLeadSearchRoute: typeof ApiLeadSearchRoute
  ApiNvidiaChatRoute: typeof ApiNvidiaChatRoute
  ApiAiWorkflowSplatRoute: typeof ApiAiWorkflowSplatRoute
  ApiAiAnalyzeTasksRoute: typeof ApiAiAnalyzeTasksRoute
  ApiBackendSplatRoute: typeof ApiBackendSplatRoute
  ApiLearningSplatRoute: typeof ApiLearningSplatRoute
  ApiMailSplatRoute: typeof ApiMailSplatRoute
  ApiOpenclawSplatRoute: typeof ApiOpenclawSplatRoute
  ApiSpeechTranscribeRoute: typeof ApiSpeechTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workflow': {
      id: '/ai-workflow'
      path: '/ai-workflow'
      fullPath: '/ai-workflow'
      preLoaderRoute: typeof AiWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-search': {
      id: '/lead-search'
      path: '/lead-search'
      fullPath: '/lead-search'
      preLoaderRoute: typeof LeadSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openclaw-tasks': {
      id: '/openclaw-tasks'
      path: '/openclaw-tasks'
      fullPath: '/openclaw-tasks'
      preLoaderRoute: typeof OpenclawTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-generator': {
      id: '/prompt-generator'
      path: '/prompt-generator'
      fullPath: '/prompt-generator'
      preLoaderRoute: typeof PromptGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-development': {
      id: '/self-development'
      path: '/self-development'
      fullPath: '/self-development'
      preLoaderRoute: typeof SelfDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-search': {
      id: '/api/lead-search'
      path: '/api/lead-search'
      fullPath: '/api/lead-search'
      preLoaderRoute: typeof ApiLeadSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nvidia-chat': {
      id: '/api/nvidia-chat'
      path: '/api/nvidia-chat'
      fullPath: '/api/nvidia-chat'
      preLoaderRoute: typeof ApiNvidiaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/api/ai-workflow/$': {
      id: '/api/ai-workflow/$'
      path: '/api/ai-workflow/$'
      fullPath: '/api/ai-workflow/$'
      preLoaderRoute: typeof ApiAiWorkflowSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/analyze-tasks': {
      id: '/api/ai/analyze-tasks'
      path: '/api/ai/analyze-tasks'
      fullPath: '/api/ai/analyze-tasks'
      preLoaderRoute: typeof ApiAiAnalyzeTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backend/$': {
      id: '/api/backend/$'
      path: '/api/backend/$'
      fullPath: '/api/backend/$'
      preLoaderRoute: typeof ApiBackendSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/$': {
      id: '/api/learning/$'
      path: '/api/learning/$'
      fullPath: '/api/learning/$'
      preLoaderRoute: typeof ApiLearningSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/$': {
      id: '/api/mail/$'
      path: '/api/mail/$'
      fullPath: '/api/mail/$'
      preLoaderRoute: typeof ApiMailSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openclaw/$': {
      id: '/api/openclaw/$'
      path: '/api/openclaw/$'
      fullPath: '/api/openclaw/$'
      preLoaderRoute: typeof ApiOpenclawSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech/transcribe': {
      id: '/api/speech/transcribe'
      path: '/api/speech/transcribe'
      fullPath: '/api/speech/transcribe'
      preLoaderRoute: typeof ApiSpeechTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiWorkflowRoute: AiWorkflowRoute,
  BookRoute: BookRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRoute,
  FinanceRoute: FinanceRoute,
  LeadSearchRoute: LeadSearchRoute,
  MailRoute: MailRoute,
  OpenclawTasksRoute: OpenclawTasksRoute,
  ProjectsRoute: ProjectsRoute,
  PromptGeneratorRoute: PromptGeneratorRoute,
  RequestsRoute: RequestsRoute,
  SelfDevelopmentRoute: SelfDevelopmentRoute,
  TasksRoute: TasksRouteWithChildren,
  ApiLeadSearchRoute: ApiLeadSearchRoute,
  ApiNvidiaChatRoute: ApiNvidiaChatRoute,
  ApiAiWorkflowSplatRoute: ApiAiWorkflowSplatRoute,
  ApiAiAnalyzeTasksRoute: ApiAiAnalyzeTasksRoute,
  ApiBackendSplatRoute: ApiBackendSplatRoute,
  ApiLearningSplatRoute: ApiLearningSplatRoute,
  ApiMailSplatRoute: ApiMailSplatRoute,
  ApiOpenclawSplatRoute: ApiOpenclawSplatRoute,
  ApiSpeechTranscribeRoute: ApiSpeechTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
